[project]
name = "pdf-toolkit"
version = "0.1.0"
description = ""
authors = [{ name = "daroG", email = "darek.kce@gmail.com" }]
requires-python = ">=3.10,<4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pyguetzli>=1.0.14,<2",
    "PyPDF4>=1.27.0,<2",
    "pypdf>=3.5.2,<4",
    "ttkbootstrap>=1.10.1,<2",
    "eel>=0.16.0,<0.17",
    "ruff>=0.3.5,<0.4",
    "pillow>=11.0.0,<12",
]

[dependency-groups]
dev = ["pytest>=7.2.2,<8"]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["pdf_toolkit"]
module-root = ""

[build-system]
requires = ["uv_build>=0.9.1,<0.10.0"]
build-backend = "uv_build"
